# member < officer < leader < admin
#Permissions relates only to faction actions
commands-permissions:
  claim: 'leader'
  unclaim: 'leader'
  faction-add-member: 'leader'
  faction-remove-member: 'leader'
  faction-set-name: 'leader'
  faction-set-shortcut: 'leader'
  faction-set-color: 'admin'