# member < officer < leader < admin
#Permissions relates only to faction actions
commands-permissions:
  claim: 'leader'
  unclaim: 'leader'
  faction-add-member: 'leader'
  faction-remove-member: 'leader'
  faction-set-name: 'leader'
  faction-set-shortcut: 'leader'
  faction-set-color: 'leader'
  war-declare: 'leader'
  war-peace: 'leader'

localisation:
  cmd-not-found: "&cCommand not found."
  cmd-player-only: "&cCommand is player only."
  cmd-no-permission: "&cYou have not permission to perform this command."
  cmd-faction-not-found: "&cFaction not found, incorrect name or faction does not exist."
  cmd-player-not-found: "&cPlayer not found."
  cmd-claim-type-not-found: "&cGiven claim type does not exist."
  cmd-color-not-found: "&cGiven color does not exist."
  terrain-claimed: "&cCan't interact with claimed terrain unless you are at war with claim owner!"
  cant-change-owner: "&cYou can't change owner of this claim!"
  owner-changed: "&aClaim owner changed."
  target-in-faction: "&cThis player is already in faction!"
  player-added: "&aPlayer added to faction."
  target-not-member: "&ePlayer is not a faction member!"
  cant-kick-leader: "&cYou can't kick faction leader!"
  faction-exists: "&cFaction with that name already exists!"
  cant-unclaim: "&cYou can't unclaim this terrain!"
  already-at-war: "&cFaction is already in war with that faction!"
  war-declared: "&aWar has been declared."
  already-at-peace: "&cFaction is already at peace with that faction!"
  signed-peace: "&aPeace has been signed."
  color-changed: "&aFaction color changed successfully."
  already-claimed: "&cThis terrain is claimed already!"
  claimed: "&aTerrain claimed successfully."
  not-claimed: "&aThis terrain is not claimed."
  claimed-by: "&eThis terrain is claimed by: &b"
  faction-deleted: "&aFaction deleted successfully."
  factions-list: "&eFactions list: &b"
  faction-name: "&eName: &a"
  faction-shortcut: "&eShortcut: &a"
  faction-leader: "&eLeader: &a"
  faction-members: "&eMembers: &a"
  faction-enemies: "&eEnemies: &a"
  faction-core-loc: "&eCore location: &a"
